name: Create GitHub Release

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    if: startsWith(github.head_ref, 'release-')

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GITHUB_TOKEN }}
          tags: true

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Generate Changelog
        run: |
          bin/rails generate:changelog
          echo "Changelog generated and updated."

      - name: Determine Version Number
        run: |
          make determine-app-version
          echo "App Version Determined."

      - name: Create Tag
        id: create_tag
        run: |
          TAG_NAME="v$(cat VERSION)"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Commit Changelog and Version Updates
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add CHANGELOG.md VERSION
          git commit -m "Release ${{ env.TAG_NAME }}"
          git push origin ${{ github.head_ref }}

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          body: |
            ## Changelog
            $(cat CHANGELOG.md)
          draft: false
          prerelease: false
