name: Create GitHub Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          tags: true   

      # Install Ruby dependencies to run the changelog task (optional)
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Generate changelog
        run: |
          bin/rails generate:changelog
          echo "Changelog generated and updated."

      # Create a tag
      - name: Create Tag
        id: create_tag
        run: |
          TAG_NAME="v$(date +'%Y.%m.%d')"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          git tag $TAG_NAME
          git push origin $TAG_NAME

      # Create a GitHub Release
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG_NAME }}
          release_name: Release ${{ env.TAG_NAME }}
          body: |
            ## Changelog
            $(cat CHANGELOG.md)
          draft: false
          prerelease: false
