name: Create Release PR

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  create-release-pr:
    name: Create Release Pull Request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Install dependencies
        run: |
          bundle install

      - name: Generate changelog
        run: |
          echo "Generating changelog..."
          bin/rails generate:changelog 

      - name: Create a release branch
        id: create_branch
        run: |
          BRANCH_NAME="release-$(date +'%Y%m%d')"
          echo "Branch name: $BRANCH_NAME"
          git checkout -b "$BRANCH_NAME"
          echo "::set-output name=branch::$BRANCH_NAME"

      - name: Push release branch
        run: |
          git add .
          git commit -m "Prepare release"
          git push origin ${{ steps.create_branch.outputs.branch }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "Prepare release"
          branch: ${{ steps.create_branch.outputs.branch }}
          base: main
          title: "Release: ${{ steps.create_branch.outputs.branch }}"
          body: |
            ## Changes
            - Generated release branch: `${{ steps.create_branch.outputs.branch }}`
            - Changelog updated
          draft: false
