name: Prevent Main Merge

on:
  pull_request:
    branches:
      - main

jobs:
  check-branch-name:
    runs-on: ubuntu-latest
    steps:
      - name: Get current PR information
        id: get-pr-info
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            // Get the current PR data
            const pr = await github.rest.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });

            // Set outputs with current source and target branches
            core.setOutput('head_ref', pr.data.head.ref);
            core.setOutput('base_ref', pr.data.base.ref);

      - name: Check if source branch is valid for target
        run: |
          echo "Source branch: ${{ steps.get-pr-info.outputs.head_ref }}"
          echo "Target branch: ${{ steps.get-pr-info.outputs.base_ref }}"

          # Use the fetched branch information
          if [[ "${{ steps.get-pr-info.outputs.base_ref }}" == "main" && "${{ steps.get-pr-info.outputs.head_ref }}" != release-* ]]; then
            echo "Error: Only branches starting with 'release-' can be merged into main."
            exit 1
          fi
