name: Update Changelog on Release Branch

on:
  push:
    branches:
      - release-*

jobs:
  update-changelog:
    name: Update Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          tags: true   

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Generate and commit changelog
        run: |
          bin/rails generate:changelog
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add CHANGELOG.md
          git commit -m "Update changelog"
          git push
